a = input("Enter name: ")
b = int(input("Enter Maths marks: "))
c = int(input("Enter Science marks: "))
d = int(input("Enter Social Science marks: "))
e = int(input("Enter English marks: "))
f = int(input("Enter Second Language marks: "))
print("Report")
print("Name: ", a)
print("Total Marks: ", b+c+d+e+f)
print("Total Average: ", (b+c+d+e+f)/5)
